{{- if and .Values.experimental.windowsAmbientInjection.enabled (not (eq .Values.defaultRevision "")) }}
{{- $whv := dict
 "revision" .Values.defaultRevision
  "injectionPath" .Values.istiodRemote.injectionPath
  "injectionURL" .Values.istiodRemote.injectionURL
  "reinvocationPolicy" .Values.sidecarInjectorWebhook.reinvocationPolicy
  "caBundle" .Values.istiodRemote.injectionCABundle
  "namespace" .Release.Namespace }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
{{- if eq .Release.Namespace "istio-system"}}
  name: istio-sidecar-injector{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
{{- else }}
  name: istio-sidecar-injector{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}-{{ .Release.Namespace }}
{{- end }}
labels:
  istio.io/rev: {{ .Values.revision | default "default" | quote }}
  install.operator.istio.io/owning-resource: {{ .Values.ownerName | default "unknown" }}
  operator.istio.io/component: "Pilot"
  app: windows-ambient-injector
  release: {{ .Release.Name }}
  app.kubernetes.io/name: "istiod"
  {{- include "istio.labels" . | nindent 4 }}
{{- end }}
