apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: goog-http
spec:
  hosts:
  - google.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
  resolution: DNS